name: Run Python Script

on:
  workflow_dispatch:   # bisa dijalankan manual
  schedule:
    - cron: "0 0 * * *"   # jalan otomatis tiap hari jam 00:00 UTC

jobs:
  run-python:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Required untuk git push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'   # Cache pip dependencies untuk install lebih cepat

      - name: Install system dependencies for aiohttp
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python run.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.csv *.json
          git commit -m "Update CSV dan JSON hasil scraping [skip ci]" || echo "No changes to commit"
          git push
